name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        run: make

      - name: Upload 3DSX
        uses: actions/upload-artifact@v4
        with:
          name: udsploit-build
          path: *.3dsx
          if-no-files-found: error
